buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.2.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

group 'com.zegocloud.uikit.call_plugin'
version '1.0'

apply plugin: 'com.android.library'

android {

    if (project.android.hasProperty("namespace")) {
        namespace 'com.zegocloud.uikit.call_plugin'
    }

    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 28
        consumerProguardFiles 'proguard-rules.pro'
    }
}

dependencies {
    implementation "androidx.core:core:1.7.0"
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
}
